### ISSUE TITLE
Save buttom not responding

### ISSUE THREAD

**Issue by edyCooper** [andyprasetya/leaflet-CRUD#1]

**Comment by andyprasetya** [comment]
Can you describe the issue in a clearer description? -- screenshots, etc.

**Comment by andyprasetya** [comment]
1. You must have set the database (PostgreSQL/PostGIS) properly, and make sure you have also already have restored the .sql file inside the arvhives folder.
2. You must have PHP works on your server.

**Comment by edyCooper** [comment]
Thanks.
It's working already...!
